function make_character()
    local c={}
    c.x=1
    c.y=1
    c.name="Gnorlash"
    c.rank=0
    c.initiative_modifier=0
    c.dedication=150
    c.patron=nil
    c.favor=0
    c.favor_of_the_crowd=false
    c.determination=0
    c.momentum=0
    c.health_max=rnd(6)+1+15
    c.health_current=c.health_max
    c.bloodied=false
    c.aether_max=rnd(6)+1+10
    c.aether_current=c.aether_max
    c.stamina=10
    c.speed=2
    c.magic_resistance=40
    c.exhaustion=0
    c.shock=0
    c.skills={
        {skill="acrobatics",value=0},
        {skill="athletics",value=0},
        {skill="dodge",value=0},
        {skill="endurance",value=0},
        {skill="medicine",value=0},
        {skill="resolve",value=0},
        {skill="stealth",value=0},
        {skill="armor_piercing",value=0},
        {skill="axes",value=0},
        {skill="bows_and_crossbows",value=0},
        {skill="daggers_and_knives",value=0},
        {skill="firearms",value=0},
        {skill="bludgeoning",value=0},
        {skill="slingshots",value=0},
        {skill="spears_and_polearms",value=0},
        {skill="swords",value=0},
        {skill="throwing_weapons",value=0},
        {skill="unarmed_combat",value=0},
        {skill="whips_and_chains",value=0}
    }    
    c.gear={
        {slot="weapon",contents=nil},
        {slot="armor",contents=nil},
        {slot="helmet",contents=nil},
        {slot="gloves",contents=nil},
        {slot="boots",contents=nil},
        {slot="ring1",contents=nil},
        {slot="ring2",contents=nil}
    }
    return c
end